---
- name: Install Docker on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Uninstall old versions of Docker
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - docker
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc

    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Dockers official GPG key
      ansible.builtin.command:
        cmd: 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg'

    - name: Set up the stable repository
      ansible.builtin.command:
        cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update the apt package index again
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verify Docker installation
      command: docker --version
      register: docker_version_output

    - debug:
        var: docker_version_output.stdout
