- hosts: "{{ hosts }}"

  become: yes
  tasks:
    
    - name: Uninstall old versions of Docker
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      loop:
        - docker
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc
    
    - name: install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        update_cache: yes

    - name: add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      
    - name: get ubuntu version
      command: "lsb_release -cs"
      register: ubuntu_version

    - name: add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version.stdout }} stable"
        state: present

    - name: update apt cache
      apt:
        update_cache: yes

    - name: install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
          - docker-buildx-plugin
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes